spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: root
    password: 12354678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: Abdulmalik
    password: 12345678
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  application:
    security:
      jwt:
        secret-key: e818e6b36eda0f478cafbcbbefc1d69e3e641578ae0979cc90e08cfe89d3af1c
        expiration: 8640000